# @format

version: "3"
services:
  api:
    build: .
    image: jdavault/ecs-project2
    environment:
      - MONGO_USER=mongo
      - MONGO_PASSWORD=passsword
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongo:password@localhost:27017/notes-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=posts-db
    ports:
      - "3001:3001"
  mongo:
    image: mongo
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=notes-db
    volumes:
      - mongo-db:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  prosgres-data:
